---
- name: Installing httpd
  hosts: webserver
  become: true

  tasks:
    - name: Installing httpd package
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "Redhat"
      ignore_errors: yes
    
    - name: starting httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "Redhat"
      ignore_errors: yes

    - name: Installing apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: starting apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index.html file
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        mode: 0666
    


