---
- name: Installing packages
  hosts: webserver
  become: true

  tasks:
    - name: Installing packages
      yum:
        name: ['git', 'mysql', 'tree', 'docker*', 'which', 'wget']
        state: installed

