---
- name: Installing package
  hosts: webserver
  # become: true

  tasks:
    - name: Installing git
      yum:
        name: git
        state: installed

    - name: Install the latest version of Apache
      yum:
        name: httpd
        state: latest

