---
- name: Installing httpd
  hosts: webserver
  become: true

  tasks:
    - name: Installing httpd package
      yum:
        name: httpd
        state: installed
      notify: starting httpd service

  handlers:
    - name: starting httpd service
      service:
        name: httpd
        state: started

